In [ ]:
#Data okuyoruz
import pandas as pd
df = pd.read_csv("tr_yorumlar.csv")
df.shape

(567, 2)

In [ ]:
#Data değerleri kontrol ediyourz
df.head(10)

                                               yorum     duygu
0  Kugerr makine ve Marmaris servis Batu Ticaret ...  negative
1               ürün gayet iyi ama kurulum sıkıntılı  negative
2  fiyatına göre cok iyi  montajı kendım yaptım s...  positive
3  birkaç ay kullanıp atarsınız, malzeme kalitesi...  negative
4  çok kötü bir film bence,ayrıca hiçte etkilenme...  negative
5  ürün güzel memnun kaldım teşekkür ediyorum hep...  positive
6  fiyatına göre iyi sadece plastik aksamları bir...  negative
7  sanat için sanat derler ya, bu da vahset için ...  negative
8  kesinlikle vakit geçirmeye değmez. oldukça köt...  negative
9  ürün 2 günde elime ulaştı, fiyatına göre alına...  positive

In [ ]:
#Null değerler ve type 
df.dtypes
df.isnull().sum()

yorum    0
duygu    0
dtype: int64

In [5]:
#Label dağılımı 
df["yorum"].value_counts()  # kolon adını kendi datana göre değiştir
df["duygu"].value_counts(normalize=True)

duygu
positive    0.504409
negative    0.495591
Name: proportion, dtype: float64

Label dağılım positive 51 negative 49 çıktı buda dengeli bir veri yapısı veriyor

#Data genel değerlendirmesine bakıyoruz 
yorumlar ortlama uzunluğuna bakıyoruz datada çok kısa ve çok uzun cümleler var

In [ ]:

df["char_len"] = df["yorum"].str.len()  
df["word_len"] = df["yorum"].str.split().str.len()
df[["char_len","word_len"]].describe()

         char_len    word_len
count  567.000000  567.000000
mean   129.158730   18.365079
std     86.582542   12.072325
min     16.000000    1.000000
25%     56.000000    8.000000
50%    114.000000   16.000000
75%    179.000000   25.000000
max    393.000000   56.000000

In [7]:
df.duplicated().sum()
df["yorum"].duplicated().sum()

np.int64(0)

#En kısa ve en uzun yorumu kontrol ediyouz 
Çok kısa ve positive olanlar var ama çok kısa vee negative olanlarda var

In [ ]:

df.loc[df["word_len"].idxmin(), "yorum"]
df.sort_values("word_len").head(5)[["yorum","duygu","word_len"]]

                         yorum     duygu  word_len
511         iyi...iyi...10/9,5  positive         1
324       gereksizlik abidesi.  negative         2
140           sesli çalışıyor.  negative         2
550  kullanamadım kiiiiiiiiiii  negative         2
89            fiyatı çok makul  positive         3

#Zıtlık bağlacını kontrol ediyourz
zıtlık bağlacı içeren yorumlar daha çok negative

In [ ]:

mask = df["yorum"].str.contains(r"\bama\b|\bfakat\b|\bancak\b", case=False, regex=True, na=False)
df[mask]["duygu"].value_counts(normalize=True)
print(mask.sum(), "yorumda zıtlık bağlacı var")

118 yorumda zıtlık bağlacı var

#Rastgele  verilere bakıyoruz data nasıl sekilleneceğine dair 
Burda yazım hataları ve farklı kategorilerden yorumlarda mevcut

In [ ]:

pd.set_option("display.max_colwidth", None)
for t in df[df["duygu"]=="negative"].sample(10, random_state=1)["yorum"]:
    print("-", t, "\n")

- en ufak kırıntıları,taşı,toprağı hiçbir şeyi çekmiyor. geri iade de edemedim. bunu alacağıma keşke uzatma kablosu ile basit bir ev elektrik süpürgesi alsaydım. çok daha memnun kalırdım. alan zarar eder.

- masa ve kitalık bölümü çok küçük,görüntüye bakmayın

- Plastik yapısı çok kırılgan. Her an başına birşey gelebilir diye kutuda gezdiriyorum. bilseydin bu kadar ince ve kırılgan olduğunu almazdım.

- Tavsiye etmiyorum. Senaryo çok havada kalmış. Sonuda kötü yapılmış. Seyrettikten sonra hemen unutmak isteyeceğiniz bir film. 4/10

- ya film için tek diğecek şeyim var oda çok sıkıcı olması.Nerdeyse uykum geliyordu.Bİraz da karışık olmasıve ve hiç heyecan olmaması uykum gelecek halini alıyor.Şiddetle tavsiye etmem.Ama inat edip izlemek istiyorum diyorsanız keyif sizin...

- sıfır maliyetle ancak bu kadar film yapılırdı.filmde o kadar çok hata var ki saymakla bitmez.laptop parçalama sahnesi bile gerçek değildi.3 bile çok bence

- arkadaşlar 9 ay kadar önce almıştım. 10400 mah değeri desteklemiyor ortalama 3000 mah' a sahip bir telefonu 3 defa deşarj halden full şarj yapması gerekirken 1 defa anca yapıyor. bazen 1 buçuk defa. ayrıca orjinal test kodunu sisteme girdiğim zaman daha önce 5 defa sorgulanmıştır diye bir ibare ile karşılaştım.

- film için kötü diye yorum yapılsa tamamda gitme demek ne onu anlamıyorum? 'gidin bu filme efendim, her filme gidin hatta.' özellikle bu tarz vadettiğini gerçekleştiren filmler için gitme diyenlere kulak tıkayın.

- berbat bir otelyemekler çok kötü odalar çok pis personel özelliklede resepsiyondakiler çok ilgisiz

- etherneti yok dreamboxla alakası yok ah keşke dreambox böyle bi şey çıkarsa piyasayı allak bullak eder

In [11]:
df.value_counts(normalize=True)

yorum                                                                                                                                                                                                    duygu     char_len  word_len
Kugerr makine ve Marmaris servis Batu Ticaret inanilmaz kotu.                                                                                                                                            negative  61        9           0.001764
ürün gayet iyi ama kurulum sıkıntılı                                                                                                                                                                     negative  36        6           0.001764
fiyatına göre cok iyi  montajı kendım yaptım sabahı bekleyemedım buyuklugu harıka                                                                                                                        positive  81        11          0.001764
birkaç ay kullanıp atarsınız, malzeme kalitesi çok kötü. suya giren bir ürün olduğu için paslanmaz olması gerekirken , vidaları paslanıyor ve elektrik bağlantıları kopuyor.                             negative  172       24          0.001764
çok kötü bir film bence,ayrıca hiçte etkilenmedim ama müzikleri çok güzel...                                                                                                                             negative  76        11          0.001764
                                                                                                                                                                                                                                           ...
kötü...cok yapay.. görüntüler cok kötü..cok abartılı.. izlemek zaman kaybı.. filmin tek güzel tarafı milla                                                                                               negative  106       14          0.001764
Film akıcılık,amaç unsurlarından hiçbirini arındırmıyor.Görsel efektler ve Charlize için izlenilebilir olsa da izlemeyin derim.                                                                          negative  127       14          0.001764
pil interneti az kullanıyorsanız abartısız net iki gün gidiyor.üstelik çabuk şarj oluyor.kamera zom 4x, 2x değil.ekranda kullanırken kolay kolay parmak izi olmadı ve henüz küçük çizikler de oluşmadı.  positive  199       28          0.001764
hayatımda izlediğim en berbat filmdi içindeki yabancıyı geçmesine çok üzüldüm o film daha yukarlarda bi yeri hakediyo bir numara o olmalıydı                                                             negative  140       21          0.001764
gereksız vasat ve sıradan bı fılme benzıyo Zeynebin sekiz günü gıbıyse harbıden yandık kı benzıyo :D                                                                                                     negative  100       16          0.001764
Name: proportion, Length: 567, dtype: float64

In [12]:
mask = df["yorum"].str.contains(r"\bama\b|\bfakat\b|\bancak\b", case=False, regex=True, na=False)
df[mask]["duygu"].value_counts(normalize=True)

duygu
negative    0.694915
positive    0.305085
Name: proportion, dtype: float64

In [13]:
pd.set_option("display.max_colwidth", None)
for t in df[df["duygu"]=="positive"].sample(10, random_state=1)["yorum"]:
    print("-", t, "\n")

- üründe herhangi bir sorun yok ve  aldıktan iki gün sonra bana teslim edildi çok hızlılar.

- akıllı saat almak isteyenler düşünsün derim. fiyatı oldukça uygun. mağazalardan 200 lira daha ucuza aldım

- Her şey çok iyiydi. Etstura teşekkür ederim onların tavsiye üzerine gittim mennunum.

- bu fiyata ve kaliteli ürün kesinlikle alacak olanlara hiç düşünmeden almalarını tavsiye ederim. firmaya da hızlı kargo için teşekkür ederim.

- kargosu çok hizli di̇yarbakir gi̇bi̇ yere 2 gunde geldi̇.apart sorunu var.netten i̇zledi̇ğm vi̇deolarda deği̇şi̇k aparatlardan bahsedi̇yordu.onlari da alinca artik si̇zi̇ kimse tutamaz.sessi̇z ve seri̇ çali̇isiyo.şi̇ddetle tavsiye ederi̇m

- ürün süper hızlı gönderi olmasına rağmen 3.günde elime ulaştı. hepsiburada.com'dan müşteri hizmetleri gecikmeyle ilgili bildirimlerde bulundular. fakat benim için bir sonraki alışverişimi etkileyecek yönde bir deneyim oldu. ürüne gelince ürün yorumlarda da belirtildiği gibi fiyatına göre gayet ideal, kaliteli bir ürün. beğendim.

- jett i aldık, rahat ettik,

- makina çok hafif, çok güzel. beklediğimden çok çok iyi çıktı. hepsiburada.com zaten çok güzel bir sistem... kesinlikle tavsiye ederim.

- ürün harika istediğim gibi geldi. i̇ç kısmını merak etmiştim, iç kısmı metal değil metal cinsinde bir plastikten yapılmıştır siyah renktedir. dış beyaz görünen kısım metaldir. ayrıca alt tabanında kaydırmaz sünger bulunmaktadır. 500 ml 'lik ağız kısmında kapağını açmadan içebileceğiniz kısım bulunmaktadır.

- ürün 23 saat içinde elime ulaştı .gerçekten gayet güzel.yanında gelen yüzükte oldukça hoş eşim için güzel bir anneler günü hediyesi olacak.

#Küçük harf çevirme gibi işlemde lower yeine PyICU  kullandım küçük harf yaparken yakın harfleri farklı bir hafre cevirebilir diye
#Zıtlık bağlaç stopwords de ama ki gib işlemler normalde çıkarmamız gerekirken cümle içinde anlamına göre çıkarma uygulammız gerek
#Stemming/lemmatization yapımında ene yayın kullanılan zeyrek kullanabilirz n-gram işimizi görmeye bilir 
#Tekrarlayan harf ve noktalar kaldırdım

In [ ]:
!pip install pipwin

Requirement already satisfied: pipwin in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (0.5.2)
Requirement already satisfied: docopt in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (0.6.2)
Requirement already satisfied: requests in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (2.34.2)
Requirement already satisfied: pyprind in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (2.11.3)
Requirement already satisfied: six in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (1.17.0)
Requirement already satisfied: beautifulsoup4>=4.9.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (4.15.0)
Requirement already satisfied: js2py in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (0.74)
Requirement already satisfied: packaging in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (26.3)
Requirement already satisfied: pySmartDL>=1.3.1 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from pipwin) (1.3.4)
Requirement already satisfied: soupsieve>=1.6.1 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from beautifulsoup4>=4.9.0->pipwin) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from beautifulsoup4>=4.9.0->pipwin) (4.16.0)
Requirement already satisfied: tzlocal>=1.2 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from js2py->pipwin) (5.4.4)
Requirement already satisfied: pyjsparser>=2.5.1 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from js2py->pipwin) (2.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from requests->pipwin) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from requests->pipwin) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from requests->pipwin) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from requests->pipwin) (2026.7.22)
Requirement already satisfied: tzdata in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from tzlocal>=1.2->js2py->pipwin) (2026.3)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
!pipwin install pyicu

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\data-science-project\data-science-project-54\.venv-1\Scripts\pipwin.exe\__main__.py", line 4, in <module>
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\pipwin\command.py", line 28, in <module>
    from . import pipwin, __version__
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\pipwin\pipwin.py", line 13, in <module>
    import js2py
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

In [17]:
!pip install zeyrek

Requirement already satisfied: zeyrek in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (0.1.3)
Requirement already satisfied: nltk>=3 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from zeyrek) (3.10.2)
Requirement already satisfied: defusedxml in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from nltk>=3->zeyrek) (0.7.1)
Requirement already satisfied: click in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from nltk>=3->zeyrek) (8.4.2)
Requirement already satisfied: joblib in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from nltk>=3->zeyrek) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from nltk>=3->zeyrek) (2026.7.19)
Requirement already satisfied: tqdm in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from nltk>=3->zeyrek) (4.70.0)
Requirement already satisfied: colorama in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from click->nltk>=3->zeyrek) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import re
import zeyrek



import logging
logging.getLogger("zeyrek").setLevel(logging.ERROR)
analyzer = zeyrek.MorphAnalyzer()

def preprocess(text: str) -> str:
   
    # 1 Türkçe Stop-Word listesi
    standart_stopwords = {
        "ve", "veya", "da", "de", "ile", "için", "çünkü", "bir", "bu", "şu", "o",
        "ki", "mi", "mı", "mu", "mü", "gibi", "hem", "ise", "diye", "en", "daha",
        "böyle", "şöyle", "her", "hiç", "bazı", "tüm", "hep", "kendi",
        "ama", "fakat", "lakin", "ancak", "oysa", "halbuki", "yine", "rağmen"
    }
    
    #Silinmesini istemediğimiz zıtlık bağlaçları
    korunacak_zitlik_baglaclari = {
        "ama", "fakat", "lakin", "ancak", "oysa", "halbuki", "yine", "rağmen", "oysaki"
    }
    
    # Filtre  oluşturma
    temizlik_listesi = standart_stopwords - korunacak_zitlik_baglaclari

    #Türkçe Uyumlu Küçük Harfe Çevirme 
    harf_haritasi = {'İ': 'i', 'I': 'ı'}
    metin = text
    for buyuk, kucuk in harf_haritasi.items():
        metin = metin.replace(buyuk, kucuk)
    metin = metin.lower()

    #  Tekrar eden Harfleri Normalize 
    metin = re.sub(r'(\w)\1{2,}', r'\1', metin)

    # --- ADIM 3: Noktalama Temizliği (URL, E-posta ve Sayı Korumalı) ---
    # E-posta ve URL'leri korumak için etiketleme
    urls = re.findall(r'https?://\S+|www\.\S+', metin)
    emails = re.findall(r'\S+@\S+', metin)
    
    for i, url in enumerate(urls):
        metin = metin.replace(url, f" [URL_{i}] ")
    for i, email in enumerate(emails):
        metin = metin.replace(email, f" [EMAIL_{i}] ")

    # Kelime başı/sonu ve bağımsız noktalama işaretlerini temizleme
    metin = re.sub(r'(?<!\w)[.,!?;:"\'()\[\]{}–\-—<>‘“’”（）«»*_+~`|=#]+', ' ', metin)
    metin = re.sub(r'[.,!?;:"\'()\[\]{}–\-—<>‘“’”（）«»*_+~`|=#]+(?!\w)', ' ', metin)
    metin = re.sub(r'\s+[.,!?;:"\'()\[\]{}–\-—<>‘“’”（）«»*_+~`|=#]+\s+', ' ', metin)

    # E-posta ve URL'leri geri yükleme
    for i, url in enumerate(urls):
        metin = metin.replace(f" [URL_{i}] ", url)
    for i, email in enumerate(emails):
        metin = metin.replace(f" [EMAIL_{i}] ", email)

    # Fazla boşlukları temizleme
    metin = re.sub(r'\s+', ' ', metin).strip()

    #  Zeyrek ile Tokenize ve Lemmatization -
    analiz_sonuclari = analyzer.analyze(metin)
    
    kok_kelimeler = []
    
    for kelime_analizi in analiz_sonuclari:
     if not kelime_analizi:
        continue

     en_olasi_analiz = kelime_analizi[0]
     orijinal_kelime = en_olasi_analiz.word.lower()
     kelime_koku = getattr(en_olasi_analiz, 'lemma', en_olasi_analiz).lower()

    # Zıtlık bağlaçlarında zeyrek'e güvenme, orijinali kullan
     if orijinal_kelime in korunacak_zitlik_baglaclari:
        kelime_koku = orijinal_kelime

    # Zeyrek tanıyamadıysa (Unk), orijinali kullan
     if kelime_koku == "unk":
        kelime_koku = orijinal_kelime

     if not kelime_koku.isalpha():
        continue

     if kelime_koku not in temizlik_listesi:
        kok_kelimeler.append(kelime_koku)  
    # Temizlenmiş metni birleştirerek döndür
    processed_text = " ".join(kok_kelimeler)
    return processed_text

Ön işleme fonksiyonu test etme 
Girinti hatası düzeltildi 
Bilinmeyen kelimlerde temizlendi

In [ ]:

for ornek in df["yorum"].head(5):
    print("ORİJİNAL:", ornek)
    print("İŞLENMİŞ:", preprocess(ornek))
    print()

ORİJİNAL: Kugerr makine ve Marmaris servis Batu Ticaret inanilmaz kotu.
İŞLENMİŞ: kugerr maki marmaris servis batu ticaret inanilmaz kot

ORİJİNAL: ürün gayet iyi ama kurulum sıkıntılı
İŞLENMİŞ: ürün gayet iyi ama kurul sıkıntı

ORİJİNAL: fiyatına göre cok iyi  montajı kendım yaptım sabahı bekleyemedım buyuklugu harıka
İŞLENMİŞ: fiyat göre cok iyi montaj kendım yapmak sabah bekleyemedım buyuklugu harıka

ORİJİNAL: birkaç ay kullanıp atarsınız, malzeme kalitesi çok kötü. suya giren bir ürün olduğu için paslanmaz olması gerekirken , vidaları paslanıyor ve elektrik bağlantıları kopuyor.
İŞLENMİŞ: birkaç ay kullanmak atmak malzeme kalite çok kötü su girmek ürün olmak paslanmaz olmak gerekmek vida paslanmak elektrik bağlantı kopmak

ORİJİNAL: çok kötü bir film bence,ayrıca hiçte etkilenmedim ama müzikleri çok güzel...
İŞLENMİŞ: çok kötü film bence ayrıca etkilemek ama müzik çok güzel

In [ ]:
sonuc = analyzer.analyze("ürün gayet iyi ama kurulum sıkıntılı")
print(len(sonuc))
print(sonuc[0])
print(dir(sonuc[0][0]))  
#hangi kelimelerde hata yaptığını yakalmaya calıstım

6
[Parse(word='ürün', lemma='ürün', pos='Noun', morphemes=['Noun', 'A3sg'], formatted='[ürün:Noun] ürün:Noun+A3sg'), Parse(word='ürün', lemma='ürümek', pos='Verb', morphemes=['Verb', 'Pass', 'Verb', 'Imp', 'A2sg'], formatted='[ürümek:Verb] ürü:Verb|n:Pass→Verb+Imp+A2sg')]
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__match_args__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_asdict', '_field_defaults', '_fields', '_make', '_replace', 'count', 'formatted', 'index', 'lemma', 'morphemes', 'pos', 'word']

In [ ]:
import time
başla = time.time()
df["yorum_temiz"] = df["yorum"].apply(preprocess)
print(f"Süre: {time.time() - başla:.1f} saniye")
#Süre testi

Süre: 10.0 saniye

In [22]:
(df["yorum_temiz"].str.strip() == "").sum()

np.int64(0)

In [23]:
df["temiz_word_len"] = df["yorum_temiz"].str.split().str.len()
df[["word_len","temiz_word_len"]].describe()

         word_len  temiz_word_len
count  567.000000      567.000000
mean    18.365079       15.368607
std     12.072325       10.038791
min      1.000000        1.000000
25%      8.000000        7.000000
50%     16.000000       14.000000
75%     25.000000       21.000000
max     56.000000       49.000000

#Trian Test Split
klasik yöntem 80 20 ayrıdım datayı

In [ ]:

from sklearn.model_selection import train_test_split

X = df["yorum_temiz"]
y = df["duygu"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print(X_train.shape, X_test.shape)
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

(453,) (114,)
duygu
positive    0.503311
negative    0.496689
Name: proportion, dtype: float64
duygu
positive    0.508772
negative    0.491228
Name: proportion, dtype: float64

İlk yaklasım TF-IDF + Logistic Regression
`ngram_range=(1,2)` kullanıldı bazı duygu yapılarını daha iyi yaklaması için . `max_features=3000` ve `min_df=2` ile sözlüğü sınırlandırıldı.

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(ngram_range=(1,2), max_features=3000, min_df=2)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print(X_train_tfidf.shape, X_test_tfidf.shape)

(453, 1132) (114, 1132)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, classification_report

logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train_tfidf, y_train)

y_pred_train = logreg.predict(X_train_tfidf)
y_pred_test = logreg.predict(X_test_tfidf)

f1_train = f1_score(y_train, y_pred_train, pos_label="positive")
f1_test = f1_score(y_test, y_pred_test, pos_label="positive")

print(f"Train F1: {f1_train:.3f}")
print(f"Test F1: {f1_test:.3f}")
print()
print(classification_report(y_test, y_pred_test))

Train F1: 0.937
Test F1: 0.813

              precision    recall  f1-score   support

    negative       0.84      0.73      0.78        56
    positive       0.77      0.86      0.81        58

    accuracy                           0.80       114
   macro avg       0.80      0.80      0.80       114
weighted avg       0.80      0.80      0.80       114

Train F1 = 0,937, Test F1 = 0,813. Aradaki fark (0,124) hafif bir overfitting'e işaret ediyor

In [27]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (5.7.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (5.15.0)
Requirement already satisfied: tokenizers>=0.19 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (0.22.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (1.27.0)
Requirement already satisfied: torch>=1.11.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (2.13.0)
Requirement already satisfied: numpy>=1.20.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (2.4.3)
Requirement already satisfied: scikit-learn>=0.22.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: typing_extensions>=4.5.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sentence-transformers) (4.70.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.32.2)
Requirement already satisfied: fsspec>=2023.5.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.3.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools>=77.0.3 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from torch>=1.11.0->sentence-transformers) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: colorama in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: regex>=2025.10.22 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.7.19)
Requirement already satisfied: typer in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in d:\data-science-project\data-science-project-54\.venv-1\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
from sentence_transformers import SentenceTransformer

model_name = "emrecan/bert-base-turkish-cased-mean-nli-stsb-tr"
embed_model = SentenceTransformer(model_name)

d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3926.64it/s]

İkinci yaklasım  Türkçe BERT Embedding + Logistic Regression
İkinci yaklaşım için embedding modeline hafif  bir temizlik uyguluyoruz — TF-IDF'teki ağır ön işlemeden (stopword silme, lemmatization) kasıtlı olarak farklı. Çünkü BERT tabanlı modeller cümlenin bağlamından (kelime sırası, ekler, noktalama) faydalanıyor.

In [30]:
def hafif_temizle(text: str) -> str:
    metin = text.lower()  # Türkçe İ/ı sorunundan kaçınmak için istersen harf_haritasini burada da kullanabilirsin
    metin = re.sub(r'(\w)\1{2,}', r'\1', metin)  # tekrarlayan harfleri normalize et
    metin = re.sub(r'\s+', ' ', metin).strip()   # fazla boşlukları temizle
    return metin

df["yorum_hafif"] = df["yorum"].apply(hafif_temizle)

In [31]:
X_train_hafif = df.loc[X_train.index, "yorum_hafif"]
X_test_hafif = df.loc[X_test.index, "yorum_hafif"]

X_train_emb = embed_model.encode(X_train_hafif.tolist(), show_progress_bar=True)
X_test_emb = embed_model.encode(X_test_hafif.tolist(), show_progress_bar=True)

print(X_train_emb.shape, X_test_emb.shape)

Batches: 100%|██████████| 15/15 [02:13<00:00,  8.89s/it]
Batches: 100%|██████████| 4/4 [00:47<00:00, 11.87s/it]

(453, 768) (114, 768)

In [32]:
logreg_emb = LogisticRegression(max_iter=1000, random_state=42)
logreg_emb.fit(X_train_emb, y_train)

y_pred_train_emb = logreg_emb.predict(X_train_emb)
y_pred_test_emb = logreg_emb.predict(X_test_emb)

f1_train_emb = f1_score(y_train, y_pred_train_emb, pos_label="positive")
f1_test_emb = f1_score(y_test, y_pred_test_emb, pos_label="positive")

print(f"Train F1 (embedding): {f1_train_emb:.3f}")
print(f"Test F1 (embedding): {f1_test_emb:.3f}")
print()
print(classification_report(y_test, y_pred_test_emb))

Train F1 (embedding): 1.000
Test F1 (embedding): 0.847

              precision    recall  f1-score   support

    negative       0.85      0.82      0.84        56
    positive       0.83      0.86      0.85        58

    accuracy                           0.84       114
   macro avg       0.84      0.84      0.84       114
weighted avg       0.84      0.84      0.84       114

### İlk embedding sonucu 
Train F1 = 1,000, Test F1 = 0,847. Train F1'in tam 1,000 olması ciddi bir overfitting işareti — model train verisindeki her örneği ayırt edebiliyor, bu da gerçek bir örüntü öğrenmekten çok ezberlemiş demek oluyor

### C parametresini deniyoruz
Varsayılan ayarla (C=1.0) eğitilen embedding modelinde Train F1 = 1.000 çıktı — yani model train verisini ezberlemiş. Bunun düzelip düzelmediğini görmek için kontrol ediyorum

In [ ]:
#Model ezberleyip ezberlemediği kontrol ediyoruz
for C in [0.01, 0.1, 1.0]:
    m = LogisticRegression(max_iter=1000, random_state=42, C=C)
    m.fit(X_train_emb, y_train)
    f1_tr = f1_score(y_train, m.predict(X_train_emb), pos_label="positive")
    f1_te = f1_score(y_test, m.predict(X_test_emb), pos_label="positive")
    print(f"C={C}: Train F1={f1_tr:.3f}, Test F1={f1_te:.3f}")

C=0.01: Train F1=0.915, Test F1=0.879
C=0.1: Train F1=0.985, Test F1=0.835
C=1.0: Train F1=1.000, Test F1=0.847

### Regularization (C) denemesi sonucu
| C | Train F1 | Test F1 |
|---|---|---|
| 0,01 | 0,915 | **0,879** |
| 0,1 | 0,985 | 0,835 |
| 1,0 | 1,000 | 0,847 |

C=0,01'de hem overfitting neredeyse ortadan kalkıyor (train-test farkı 0,15'ten 0,04'e düşüyor) hem de Test F1 en yüksek seviyeye çıkıyor. Bu en iyi model oluyor

In [34]:
logreg_emb_final = LogisticRegression(max_iter=1000, random_state=42, C=0.01)
logreg_emb_final.fit(X_train_emb, y_train)

LogisticRegression(C=0.01, max_iter=1000, random_state=42)

In [35]:
y_pred_final = logreg_emb_final.predict(X_test_emb)
print(classification_report(y_test, y_pred_final))

              precision    recall  f1-score   support

    negative       0.88      0.88      0.88        56
    positive       0.88      0.88      0.88        58

    accuracy                           0.88       114
   macro avg       0.88      0.88      0.88       114
weighted avg       0.88      0.88      0.88       114

### Final embedding modeli sonucu
C=0,01 ile eğitilen final modelde precision/recall/f1 her iki sınıf için de dengeli çıktı 

**Genel karşılaştırma:**

| Yaklaşım | Test F1 |
|---|---|
| TF-IDF + Logistic Regression | 0,813 |
| Embedding + Logistic Regression (C=0,01) | **0,879** |

## 5. Hata Analizi
Bu bölümde test setindeki yanlış sınıflanan yorumları üç gruba ayırıp inceliyorum: sadece TF-IDF'in yanıldığı, sadece embedding'in yanıldığı, ve ikisinin de yanıldığı yorumlar var bunları göstermek

In [ ]:
# Test setindeki orijinal yorumları da görebilmek için bir dataframe 
test_df = df.loc[X_test.index, ["yorum", "duygu"]].copy()
test_df["tfidf_tahmin"] = logreg.predict(X_test_tfidf)
test_df["embedding_tahmin"] = logreg_emb_final.predict(X_test_emb)

# Her iki model de yanılmış mı, yoksa sadece biri mi?
test_df["tfidf_dogru"] = test_df["duygu"] == test_df["tfidf_tahmin"]
test_df["embedding_dogru"] = test_df["duygu"] == test_df["embedding_tahmin"]

print("Sadece TF-IDF yanıldı:", ((~test_df["tfidf_dogru"]) & (test_df["embedding_dogru"])).sum())
print("Sadece Embedding yanıldı:", ((test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])).sum())
print("İkisi de yanıldı:", ((~test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])).sum())
print("İkisi de doğru:", ((test_df["tfidf_dogru"]) & (test_df["embedding_dogru"])).sum())

Sadece TF-IDF yanıldı: 16
Sadece Embedding yanıldı: 7
İkisi de yanıldı: 7
İkisi de doğru: 84

### Karşılaştırma sayıları
Test setindeki 114 yorumun: 84'ünde iki model de doğru, 16'sında sadece TF-IDF yanıldı (embedding düzeltti), 7'sinde sadece embedding yanıldı, 7'sinde ikisi de yanıldı. 16 vs 7 oranı, embedding'in TF-IDF'e göre net bir üstünlüğü olduğunu gösteriyor — şimdi bu gruplardaki örnekleri tek tek inceleyip örüntü arayacağım.

In [ ]:
#Karsılastırma 
pd.set_option("display.max_colwidth", None)
ikisi_de_yanildi = test_df[(~test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])]
for _, row in ikisi_de_yanildi.iterrows():
    print(f"Gerçek: {row['duygu']} | TFIDF: {row['tfidf_tahmin']} | Embedding: {row['embedding_tahmin']}")
    print(row["yorum"])
    print()

Gerçek: negative | TFIDF: positive | Embedding: positive
güzel bir  boya saçlarım eski doğallığına geri döndü. kendinizin uygulayabilmesi özellikle çok güzel bir özellik. tavsiye ediyorum. denerseniz neticeyi görürsünüz.

Gerçek: negative | TFIDF: positive | Embedding: positive
daha önce okey hisset ve rötar kullandım, onlar daha iyi performans sağlıyordu, ama buda fiyatına göre fena sayılmaz, yinede tavsiye edilebilir...

Gerçek: negative | TFIDF: positive | Embedding: positive
gerçekten fragmanı bile çok güzel merakla bekliyorum ...

Gerçek: negative | TFIDF: positive | Embedding: positive
arkadaşlar 9 ay kadar önce almıştım. 10400 mah değeri desteklemiyor ortalama 3000 mah' a sahip bir telefonu 3 defa deşarj halden full şarj yapması gerekirken 1 defa anca yapıyor. bazen 1 buçuk defa. ayrıca orjinal test kodunu sisteme girdiğim zaman daha önce 5 defa sorgulanmıştır diye bir ibare ile karşılaştım.

Gerçek: positive | TFIDF: negative | Embedding: negative
çok komik ve güzel çocuklugumun filmi

Gerçek: negative | TFIDF: positive | Embedding: positive
ürün güzel, anlatıldığı gibi ama kargo çok uzun sürdü biraz daha dikkat lütfen

Gerçek: negative | TFIDF: positive | Embedding: positive
ara kablosu çok kısa 10-12 cm bişey

### İkisi de yanılan örnekler
Bu grupta ilginç bir şey var: çoğu örnek aslında **açıkça pozitif okunan bir metin ama negative etiketlenmiş** (örn. "...tavsiye ediyorum. denerseniz neticeyi görürsünüz." → negative). Bu muhtemelen modelin hatası değil, **veri setindeki etiketleme gürültüsü** ya da kesik/eksik yorum metni — verinin kendi sınırlarını gösteren bir bulgu.

In [ ]:
#Tfıdf yanıldığı yerler 
sadece_tfidf_yanildi = test_df[(~test_df["tfidf_dogru"]) & (test_df["embedding_dogru"])]
for _, row in sadece_tfidf_yanildi.iterrows():
    print(f"Gerçek: {row['duygu']} | TFIDF tahmini: {row['tfidf_tahmin']}")
    print(row["yorum"])
    print()

Gerçek: positive | TFIDF tahmini: negative
Tek yapmanız gereken sponsorları takip etmek herkes açabildiği kadar fake açsın

Gerçek: negative | TFIDF tahmini: positive
Ya bi sktir sonradan görme varoş köpek

Gerçek: negative | TFIDF tahmini: positive
en ufak kırıntıları,taşı,toprağı hiçbir şeyi çekmiyor. geri iade de edemedim. bunu alacağıma keşke uzatma kablosu ile basit bir ev elektrik süpürgesi alsaydım. çok daha memnun kalırdım. alan zarar eder.

Gerçek: positive | TFIDF tahmini: negative
verilen parayi son kurusuna kadar hakeden bir urun

Gerçek: negative | TFIDF tahmini: positive
Kafanızın içinde beyin yerine bok var

Gerçek: negative | TFIDF tahmini: positive
taban kalitesiz, derisi yumuşak ve kalıp şekli çabuk bozuldu, 1 yıldır kullanıyorum, parası kadar ayakkabı, alternatifleri değerlendirin.

Gerçek: positive | TFIDF tahmini: negative
bu nedenle biraz daha bütçe ayırıp, lumia 640 serisinden bir model tercih edilmeli.

Gerçek: negative | TFIDF tahmini: positive
gereksız vasat ve sıradan bı fılme benzıyo Zeynebin sekiz günü gıbıyse harbıden yandık kı benzıyo :D

Gerçek: positive | TFIDF tahmini: negative
alelade bir diyet kitabı değildir.

Gerçek: negative | TFIDF tahmini: positive
Beklediğimi bulamadım birkaçının oyunculuğu iyi ama diğerleri için aynı şeyi söyleyemeceğim.vakti bol arkadaşlarıma tavsiye ederim. Saygılarımla..

Gerçek: negative | TFIDF tahmini: positive
sokaktaki köpeklere verdim.yemediler.sokak kedilerine verdim onlarda yemediler. 3 gün önce koyduğum kuru mamalar halan yerinde duruyor.kesinlikle tavsiye etmiyorum.

Gerçek: positive | TFIDF tahmini: negative
bir kere şunu artık kabul ettim ki durex kondom konusunda dünya da bir numara, hepsini denemiş biri olarak diyorum ki bundan ötesi yok, kesinlikle artık hep durex alacağım...

Gerçek: positive | TFIDF tahmini: negative
bu klavyeyi rahat bir kullanım için tercih ettim. i̇stediğim zaman kucağıma alıp kullanabiliyorum.fazla yer kaplamıyor zaten.ama sessiz tuş demelerine rağmen tuşlardan baya ses geliyor.ürün 1. kalite bunu da belirteyim.

Gerçek: negative | TFIDF tahmini: positive
2 yaşında oğlum için aldım ve devamlı kullandığım bez, fakat 3 gün önce aldığım paket çok kötü çıktı,i̇ncelmiş ve çok sızdırma yapıyor. fiyat kampanya yaptıkça kaliteyi düşürüyorlar, i̇ade edeceği̇m....

Gerçek: negative | TFIDF tahmini: positive
git gelme buraya sakın gelirsen bacağını kırarım

Gerçek: positive | TFIDF tahmini: negative
vaat ettiği her şeyi yapıyor. tefal kalitesi bambaşka

tf-ıfd yanıldığı yerler 
-Argo Küfür olan yerde yanılıyor 
-Zıtlıklarda ve olumsuzlamada yanılıyor

In [ ]:
#Embeding yanıldığı yerler 
sadece_emb_yanildi = test_df[(test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])]
for _, row in sadece_emb_yanildi.iterrows():
    print(f"Gerçek: {row['duygu']} | Embedding tahmini: {row['embedding_tahmin']}")
    print(row["yorum"])
    print()

Gerçek: positive | Embedding tahmini: negative
Çok çok fazla çökmüş burada

Gerçek: positive | Embedding tahmini: negative
bu ağırlıklar bi harika dostum.boyası azcık özensiz azcık da dökülmüş gibi amma bu fiyata 2x5kg müthiş

Gerçek: negative | Embedding tahmini: positive
keanu reeves&#39;i matrix serisinden sonra gozumuzden dusmesini saglayan film(!)

Gerçek: positive | Embedding tahmini: negative
Tesıs guzel ama cok devasa buyuk oldugu ıcın ısıtma problemı vardı restorantı bıraz küçüktü yemek kalitesini düşük gördüm.

Gerçek: positive | Embedding tahmini: negative
buyuk olduğundan kullanışlı degil malesef. ancak bu fiyata gayet iyi.

Gerçek: positive | Embedding tahmini: negative
tabi bu seviyeye getirene kadar hata yaparsanız , veya şablona dikkatli bakmazsanız söküp tekrar takmak zorunda kalacaksınız ve o anlarda internetten aldığınıza pişman olabilirsiniz. ancak dikkatli ve 2-3 kişi yaparsanız sizin için daha hızlı ve rahat olur.

Gerçek: positive | Embedding tahmini: negative
çok tv seyreden bir aile değiliz. çocuklar istiyor diye aldık. fiyatına göre çok iyi.

### Embedding'in yanıldığı yerler — zayıf yönü
Burada  yanıldığı örneklerin çoğu ters sıralı zıtlık cümleleri olumsuz başlayıp "ama/ancak" ile pozitife dönen cümleler. 

Bunun muhtemel sebebi: model, veride "ama/ancak"ın çoğunlukla negatife işaret ettiği genel örüntüyü çok iyi öğrenmiş (EDA'daki %69,5 bulgusu), ama bu örüntünün istisnalarında (nadir görülen ters sıralı cümlelerde) bu genellemeye fazla güvenip yanılıyor.

**Genel sonuç:** Embedding yöntemi, klasik yöntemin kaçırdığı bağlamsal ipuçlarını (negation, argo/küfür, cümle geneli) yakalayarak daha yüksek f1 elde ediyor, ama kendi öğrendiği istatistiksel örüntüye fazla bağlanabildiği durumlarda hataya düşüyor. Bu yüzden üretimde bu tip yorumları düşük güvenle işaretleyip insan gözden geçirmesine yönlendirmeli.